// <auto-generated />
using BdGeographicalData.Shared;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BdGeographicalData.Migrations
{
    [DbContext(typeof(BdGeographicalDataDbContext))]
    [Migration("20231120065111_initial migration")]
    partial class initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("BdGeographicalData.Api.District.Entity.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BanglaName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("DivisionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.HasIndex("EnglishName", "DivisionId")
                        .IsUnique();

                    b.ToTable("Districts", (string)null);
                });

            modelBuilder.Entity("BdGeographicalData.Api.Division.Entity.Division", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BanglaName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BanglaName")
                        .IsUnique();

                    b.HasIndex("EnglishName")
                        .IsUnique();

                    b.ToTable("Divisions", (string)null);
                });

            modelBuilder.Entity("BdGeographicalData.Api.SubDistrict.Entity.SubDistrict", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BanglaName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("DistrictId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("EnglishName", "DistrictId")
                        .IsUnique();

                    b.ToTable("SubDistricts", (string)null);
                });

            modelBuilder.Entity("BdGeographicalData.Api.District.Entity.District", b =>
                {
                    b.HasOne("BdGeographicalData.Api.Division.Entity.Division", "Division")
                        .WithMany("Districts")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Division_Districts");

                    b.Navigation("Division");
                });

            modelBuilder.Entity("BdGeographicalData.Api.SubDistrict.Entity.SubDistrict", b =>
                {
                    b.HasOne("BdGeographicalData.Api.District.Entity.District", "District")
                        .WithMany("SubDistricts")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_District_SubDistricts");

                    b.Navigation("District");
                });

            modelBuilder.Entity("BdGeographicalData.Api.District.Entity.District", b =>
                {
                    b.Navigation("SubDistricts");
                });

            modelBuilder.Entity("BdGeographicalData.Api.Division.Entity.Division", b =>
                {
                    b.Navigation("Districts");
                });
#pragma warning restore 612, 618
        }
    }
}
